version: '3'

services:
  php:
    build:
      context: .
    volumes:
      - ./:/var/www/larapay:delegated

  web:
    image: nginx:1.18
    working_dir: /var/www/larapay
    volumes:
      - ./:/var/www/larapay:delegated
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - "1905:80"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ~/data/db/mysql/larapay:/var/lib/mysql:delegated
    ports:
      - "3310:3306"
